# Generated by Django 4.0.4 on 2022-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[(0, 'Bullet'), (1, 'Food'), (2, 'Travel'), (3, 'Sport')], max_length=6),
        ),
    ]
