# Generated by Django 4.0.4 on 2022-05-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_userprofile_userprof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprof',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userprof',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='user_permissions',
        ),
    ]
